name = input("What is your name: ")
age = input("how old are you: ")
colour = input("What is your favourite colour: ")
animal = input("What is your favourite animal: ")
print("You are called " +name)
print( "You are " + age + " years old")
print("Your favourite colour is " +colour)
print("Your favourite animal is a " +animal)
print("Thank you for answering my questions. \nHave a nice day")
