L = int(input("What amount (£) is being borrowed? "))
i = int(input("What annual rate of interest is being charged? "))
n = int(input("How many months needed to pay back the loan? "))
M = L*((i/100)*(1+(i/100))*n) / ((1+(i/100))*n-1)
print(L)
print ('with an annual interest rate of: ')
print(i)
print("over the following number of months")
print(n)
print("your monthly payment will be £:")
print(round(M,2))
